# Generated by Django 4.0.6 on 2022-07-26 17:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auto_part',
            managers=[
                ('lst_of_all_parts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='brand_of_car',
            managers=[
                ('lst_of_all_brands', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='part_category',
            managers=[
                ('lst_of_all_categories', django.db.models.manager.Manager()),
            ],
        ),
    ]
