# Generated by Django 4.0.6 on 2022-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_auto_part_managers_alter_brand_of_car_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_of_car',
            name='img_of_brand',
            field=models.FileField(default=0, upload_to='brands_images/', verbose_name='Фото моделі'),
            preserve_default=False,
        ),
    ]
