# Generated by Django 4.0.6 on 2022-08-17 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_auto_part_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_part',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Фото 2:'),
        ),
        migrations.AddField(
            model_name='auto_part',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Фото 3:'),
        ),
        migrations.AlterField(
            model_name='auto_part',
            name='date_create',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Останній раз змінено:'),
        ),
        migrations.AlterField(
            model_name='auto_part',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name="Фото 1(обов'язкове):"),
        ),
    ]
