# Generated by Django 4.0.6 on 2022-08-17 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_part_image_2_auto_part_image_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(default=datetime.datetime.today, verbose_name='Коли було зроблене замовлення:')),
                ('price_total', models.IntegerField(verbose_name='Ціна замовлення:')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону:')),
                ('product', models.TextField(verbose_name='Замовлені запчастини:')),
            ],
        ),
    ]
