# Generated by Django 4.0.6 on 2022-07-26 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_of_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_brand', models.CharField(max_length=25, verbose_name='brand name')),
            ],
            options={
                'verbose_name': 'Марка автомобіля',
                'verbose_name_plural': 'Марки автомобілів',
                'ordering': ['name_of_brand'],
            },
            managers=[
                ('lst_of_all_categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_of_type', models.FileField(upload_to='type_example_images/', verbose_name='Example image')),
                ('name_of_type', models.CharField(max_length=25, verbose_name='Type name')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.type_of_part')),
            ],
            options={
                'verbose_name': 'Тип запчастини',
                'verbose_name_plural': 'Типи запчастин',
                'ordering': ['name_of_type'],
            },
        ),
        migrations.CreateModel(
            name='Part_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_category', models.CharField(max_length=25, unique=True, verbose_name='Name of category')),
                ('img_of_category', models.FileField(upload_to='category_images/', verbose_name='Фото категорій запчастин')),
                ('part_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.type_of_part', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name_of_category'],
            },
        ),
        migrations.CreateModel(
            name='Model_of_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_of_model', models.FileField(upload_to='models_images/', verbose_name='Фото моделі')),
                ('name_of_model', models.CharField(max_length=25, unique=True, verbose_name='Model name')),
                ('model_of_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand_of_car', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Модель автомобіля',
                'verbose_name_plural': 'Моделі автомобілів',
                'ordering': ['name_of_model'],
            },
            managers=[
                ('lst_of_all_models', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Auto_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='products/')),
                ('state', models.BooleanField(default=False, verbose_name='Стан B/Y')),
                ('top_product', models.BooleanField(default=False, verbose_name='Найпопулярніші товари')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('car_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.brand_of_car', verbose_name='Car brand')),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.model_of_car', verbose_name='Car model')),
                ('part_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.part_category', verbose_name='Part category')),
                ('part_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.type_of_part', verbose_name='Part type')),
            ],
            options={
                'verbose_name': 'Запчастина',
                'verbose_name_plural': 'Запчастини',
                'ordering': ['name'],
            },
        ),
    ]
