# Generated by Django 4.0.6 on 2022-07-29 22:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Місто:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Коли було зроблене замовлення:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name="Ім'я:"),
        ),
        migrations.AlterField(
            model_name='order',
            name='nova_post_number',
            field=models.CharField(max_length=30, verbose_name='Номер нової пошти:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oplata_on_post',
            field=models.BooleanField(default=True, verbose_name='Оплата у відділенні:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефону:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_total',
            field=models.IntegerField(verbose_name='Ціна замовлення:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.auto_part', verbose_name='Товари:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity_total',
            field=models.IntegerField(verbose_name='Кількість всіх товарів:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='second_name',
            field=models.CharField(max_length=30, verbose_name='Прізвище:'),
        ),
    ]
