# Generated by Django 4.0.6 on 2022-07-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.TextField(default=0, verbose_name='Замовлені запчастини:'),
            preserve_default=False,
        ),
    ]
